to_do_list-final/my_app/urls.py
from django.urls import path,re_path
from . import  views
from django.conf.urls import url

app_name = 'my_app'
urlpatterns = [
    path('home/',  views.home, name='主页'),
    re_path(r'^about/$', views.about, name='关于'),
    path('search/', views.search, name='搜索'),
    path('edit/<activity_id>', views.edit, name='编辑'),
    path('delete/<activity_id>/', views.delete, name='删除'),
]

to_do_list-final/to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
import my_app.urls
from my_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(my_app.urls)),
    url(r'^reg/$', views.reg),
]

to_do_list-final/my_app/models.py
from django.db import models


class Big_subject(models.Model):
    # choices = ((1, '管理工作'), (2, '后装工作'), (3, '政治工作'))

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, )
    big_subject = models.ForeignKey(to='Big_subject', on_delete=models.CASCADE, blank=True, related_name='tasks')

    class Meta:
        unique_together = ('name', 'big_subject')

    def __str__(self):
        return self.name


class Activity(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    task = models.ForeignKey(to='Task', on_delete=models.CASCADE, related_name='activities')
    progress = models.CharField(max_length=50)
    start_time = models.DateField(max_length=50, blank=True)
    end_time = models.DateField(max_length=50, blank=True)

    def __str__(self):
        return self.name

to_do_list-final/my_app/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from django.forms import widgets
from my_app.models import Task, Big_subject, Activity


class TaskForm(forms.Form):
    big_subject = forms.ChoiceField(
        label='工作类别',
        choices=(('管理工作', '管理工作'), ('后装工作', '后装工作'), ('政治工作', '政治工作')
    ))
    task = forms.CharField(label="活动名称", widget=widgets.TextInput(attrs={"class": "form_control"}))
    activity = forms.CharField(label="活动分工", widget=widgets.TextInput(attrs={"class":"form_control"}))
    start_time = forms.DateField(label="开始时间", widget=DatePickerInput(format='%m/%d/%Y', attrs={"class":"form_control"}))
    end_time = forms.DateField(label="结束时间", widget=DatePickerInput(format='%m/%d/%Y', attrs={"class":"form_control"}))
    progress = forms.CharField(label="当前进度", widget=widgets.TextInput(attrs={"class":"form_control"}))


class Task2Form(forms.Form):
    big_subject = forms.ChoiceField(
        label='工作类别',
        choices=(('', '请选择'), ('管理工作', '管理工作'), ('后装工作', '后装工作'), ('政治工作', '政治工作'),

    ),
    required=False)
    task = forms.CharField(label="活动名称", widget=widgets.TextInput(attrs={"class": "form_control"}),required=False)
    activity = forms.CharField(label="活动分工", widget=widgets.TextInput(attrs={"class":"form_control"}), required=False)
    start_time = forms.DateField(label="起始时间", widget=DatePickerInput(format='%m/%d/%Y', attrs={"class":"form_control"}), required=False)
    end_time = forms.DateField(label="截止时间", widget=DatePickerInput(format='%m/%d/%Y', attrs={"class":"form_control"}), required=False)
    progress = forms.CharField(label="当前进度", widget=widgets.TextInput(attrs={"class":"form_control"}), required=False)

to_do_list-final/my_app/views.py
from django.shortcuts import render,redirect
from .models import Big_subject, Task, Activity
from .forms import TaskForm, Task2Form
from django.http import HttpResponse
# Create your views here.

# Create your views here.


def home(request):
    # if request.method == "POST":
    #     if request.POST['添加计划'] == '':
    #         return render(request, "home.html", {'警告':'请输入内容'})
    #     else:
    #         content = {"清单": Activity.objects.all()}
    #         return render(request, "home.html", content)
    if request.method == "GET":
        content = {"清单": Activity.objects.all()}
        return render(request, "home.html", content)



def edit(request, activity_id):
    if request.method == "POST":
        cur_obj = Activity.objects.get(id=activity_id)
        form_obj = TaskForm(request.POST)
        if form_obj.is_valid():
            cur_obj.name = form_obj.cleaned_data['activity']
            cur_obj.task.big_subject.name = form_obj.cleaned_data['big_subject']
            cur_obj.task.name= form_obj.cleaned_data['task']
            cur_obj.start_time = form_obj.cleaned_data['start_time']
            cur_obj.end_time = form_obj.cleaned_data['end_time']
            cur_obj.progress = form_obj.cleaned_data['progress']
            cur_obj.task.big_subject.save()
            cur_obj.task.save()
            cur_obj.save()
            return redirect("my_app:关于")
    elif request.method == "GET":
        cur_obj = Activity.objects.get(id=activity_id)
        form_obj = TaskForm(initial={'big_subject': cur_obj.task.big_subject.name,
                                     'task': cur_obj.task.name,
                                     'activity': cur_obj.name,
                                     'start_time': cur_obj.start_time,
                                     'end_time': cur_obj.end_time,
                                     'progress': cur_obj.progress,
                                     })
        current_task = {'current_form': form_obj}
        return render(request, "edit.html", current_task)

def about(request):
    if request.method == "POST":
        form_obj = TaskForm(request.POST)
        if form_obj.is_valid():
            name = form_obj.cleaned_data['activity']
            big_subject = form_obj.cleaned_data['big_subject']
            task = form_obj.cleaned_data['task']
            start_time = form_obj.cleaned_data['start_time']
            end_time = form_obj.cleaned_data['end_time']
            progress = form_obj.cleaned_data['progress']
            big_subject_obj = Big_subject.objects.get_or_create(name=big_subject)
            task_obj = Task.objects.get_or_create(name=task, big_subject=big_subject_obj[0])
            Activity.objects.get_or_create(name=name, task=task_obj[0], start_time=start_time,end_time=end_time, progress=progress)
        all_act = Activity.objects.all()
        content = {'form': form_obj, 'all_act': all_act}
        return render(request, "about.html", content)
    if request.method == "GET":
        page_num = request.GET.get("page")
        try:
            page_num = int(page_num)
        except Exception as e:
            page_num = 1

        form_obj = TaskForm()
        #total_page_number showed
        from .utils.mypage import Page
        page_obj = Page(page_num, per_page=10, max_page=7)
        html_list, former_page, next_page = page_obj.page_html(Activity)

        all_act = Activity.objects.all()[page_obj.start: page_obj.end]
        content = {'form': form_obj, 'all_act': all_act, "page_list": html_list, "former_page": former_page, "next_page": next_page, 'page_num': page_num}
        return render(request, "about.html", content)



def delete(request, activity_id):

    Activity.objects.get(id=activity_id).delete()
    return redirect("my_app:关于")


def reg(request):
    if request.method == "GET":
        a = request.GET.get("page")
        content = {'a': a}
    return render(request, 'reg.html', content)


def search(request):
    if request.method == "POST":
        form_obj = Task2Form(request.POST)
        if form_obj.is_valid():
            name = form_obj.cleaned_data['activity']
            big_subject = form_obj.cleaned_data['big_subject']
            task = form_obj.cleaned_data['task']
            start_time = form_obj.cleaned_data['start_time']
            end_time = form_obj.cleaned_data['end_time']
            progress = form_obj.cleaned_data['progress']
            select_dict = dict()
            if big_subject:
                big_sub_obj = Big_subject.objects.filter(name=big_subject).first()
                select_dict['task__big_subject'] = big_sub_obj
            if task:
                task = Task.objects.filter(name__contains=task)
                select_dict['task__in'] = task
            if name:
                select_dict['name__contains'] = name
            if start_time:
                select_dict['start_time__gt'] = start_time
            if end_time:
                select_dict['end_time__lt'] = end_time
            if progress:
                select_dict['progress'] = progress
            act_list = Activity.objects.filter(**select_dict)
            content = {'form': form_obj, 'act_list': act_list}
            return render(request, "search.html", content)

    if request.method == "GET":
        form_obj = Task2Form()
        content = {'form': form_obj}
        return render(request, "search.html", content)

to_do_list-final/my_app/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block extrahead %}   {# Extra Resources Start #}
   {{ form.media }}        {# Form required JS and CSS #}
   {% endblock %}          {# Extra Resources End #}

{% block 主体 %}
      <br>

      <h4>一款小巧、简洁的展示系统，帮你展示近期工作计划。</h4>


    <form id="form_input" action="" method = "post">
         <div class="form-row">
        {%csrf_token %}
             <div class="rol">
                 {{ form.big_subject.label }}
                 {{ form.big_subject }}
                 {{ form.big_subject.errors.0 }}
             </div> <br>
             <div class="rol">
                 {{ form.task.label }}
                 {{ form.task }}
                 {{ form.task.errors.0 }}
             </div> <br>
             <div class="rol">
                 {{ form.activity.label }}
                 {{ form.activity}}
                 {{ form.activity.errors.0}}
             </div> <br>
             <div class="rol">
                 {{ form.start_time.label }}
                 {{ form.start_time }}
                 {{ form.start_time.errors.0}}
             </div> <br>
             <div class="rol">
                 {{ form.end_time.label }}
                 {{ form.end_time }}
                 {{ form.end_time.errors.0 }}
             </div> <br>
             <div class="rol">
                 {{ form.progress.label }}
                 {{ form.progress }}
                 {{ form.progress.errors.0 }}
             </div> <br>
             <button class="btn btn-primary" type="submit"   /> 添加数据 <br>
         </div>
    </form>





<table class="table table-hover">

  <thead class="thead-light">
            <tr align="center">
                <th scope="col">序号</th>
                <th scope="col">工作类别</th>
                <th scope="col">活动名称</th>
                <th scope="col">具体项目</th>
                <th scope="col">开始时间</th>
                <th scope="col">结束时间</th>
                <th scope="col">工作进度</th>
                <th scope="col" colspan="2"> 操作</th>
            </tr>
  </thead>
    {% for activity in all_act %}
    <tr>
        <th scope="row"> {{forloop.counter}}</th>
    <td rowspan="1">{{ activity.task.big_subject }}
    </td>
          <td rowspan="1">{{ activity.task }}
    </td>
        <td rowspan="1">{{ activity.name }}
    </td>
           <td rowspan="1">{{ activity.start_time }}
    </td>
          <td rowspan="1">{{ activity.end_time }}
    </td>
          <td rowspan="1" >{{ activity.progress }}
    </td>
        <td><a class= "text-info" href="{%url 'my_app:删除' activity.id %}"> 删除 </a>
    </td>
         <td><a class= "text-info" href="{%url 'my_app:编辑' activity.id %}"> 编辑 </a>
    </td>

    </tr>

    {% endfor %}
</table>

    <nav aria-label="Page navigation">
  <ul class="pagination">
    <li>
      <a href="/about/?page={{ former_page }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {{ page_list|safe }}
    <li>
      <a href="/about/?page={{ next_page }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
  {% endblock 主体 %}



{% block my_title %}
      <br>
      <h4>一款小巧、简1洁的日程展示系统，帮你展示日常事务。</h4>
  {% endblock my_title %}

{% block 关于高亮 %}
active
{% endblock 关于高亮 %}

to_do_list-final/my_app/templates/base.html
{% load static %}
{% load bootstrap3 %}       {# imports bootstrap3 #}
   {% bootstrap_css %}         {# Embeds Bootstrap CSS #}
   {% bootstrap_javascript %}  {# Embeds Bootstrap JS #}
   {% block extrahead %}       {# Embeds Extra Resources #}
   {% endblock %}              {# Ends Extra Resources #}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title id="my_title">
{% block my_title %}
  {% endblock my_title %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link rel="stylesheet" type="text/css"  href= "{% static 'my_app/base.css' %}" >
<link href="{% block css %}
{% endblock css %}" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
  <a class="navbar-brand" href="#">单位</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item {% block 主页高亮 %}{% endblock 主页高亮 %}">
        <a class="nav-link" href="{% url 'my_app:主页' %}">前端展示</a>
      </li>

              <li class="nav-item {% block 关于高亮 %}{% endblock 关于高亮 %}">
        <a class="nav-link" href="{% url 'my_app:关于' %}">后端输入</a>
        </li>

        <li class="nav-item {% block 搜索高亮 %}{% endblock 搜索高亮 %}">
        <a class="nav-link" href="{% url 'my_app:搜索' %}">查询展示</a>
        </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0" method="POST" action="">
      {% csrf_token %}
      <input name="添加计划" class="form-control mr-sm-2" type="text" placeholder="添加计划" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
    </form>
  </div>
</nav>

<main role='main' class="container">
{% block 主体 %}

  {% endblock 主体 %}

    </main>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script></body>
</html>

to_do_list-final/my_app/templates/edit.html
{% extends "base.html" %}
{% load static %}
{% block css %}{% static 'my_app/home.css' %}{% endblock css %}

{% block 主体 %}

  <form id="form_edit" action="" method = "post">
         <div class="form-rol">
        {%csrf_token %}


    <div class="col">
        具体活动 {{ current_form }} <br>
                 </div>
<button class="btn btn-primary" type="submit"   /> 修改 <br>

             </div>

    </form>


{% endblock 主体 %}

to_do_list-final/my_app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block css %}{% static 'my_app/home.css' %}{% endblock css %}
{% block 主体 %}
<h4>一款小巧、简洁的展示系统，帮你展示近期工作计划。</h4>
    <br>
    <div class="table-responsive">
{{警告}}
<table class="table table-hover">

  <thead class="thead-light">
            <tr align="center">
                <th scope="col">序号</th>
              <th scope="col">工作类别</th>
            <th scope="col">活动名称</th>
            <th scope="col">具体项目</th>
            <th scope="col">开始时间</th>
                <th scope="col">结束时间</th>
            <th scope="col">工作进度</th>
            </tr>
  </thead>
     {% for activity in 清单 %}
    <tr>
        <th scope="row"> {{forloop.counter}}</th>
    <td rowspan="1">{{ activity.task.big_subject }}
    </td>
          <td rowspan="1">
              <a class="nav-link" href="{% url 'my_app:关于' %}">{{ activity.task }}</a>
    </td>
        <td rowspan="1">{{ activity.name }}
    </td>
           <td rowspan="1">{{ activity.start_time }}
    </td>
          <td rowspan="1">{{ activity.end_time }}
    </td>
          <td rowspan="1">{{ activity.progress }}
    </td>

    </tr>
    {% endfor %}
    <!--<tr ><td rowspan="6" valign="middle"> 管理工作</td>-->
            <!--<tr ><td rowspan="2" valign="middle"> 学法规用法规活动</td>-->
        <!--<td>动员部署</td>-->
        <!--<td>2020年2月-3月</td> <td>已完成</td>-->
        <!--</tr>-->
            <!--<tr>-->
            <!--<td >法规学习</td> <td>2020年6-10月</td>-->
            <!--<td>50%</td>  </tr>-->
<!--&lt;!&ndash;rowspan中必须指定要合并的列数目，是两行还是三行等等&ndash;&gt;-->
            <!--<tr ><td  rowspan="3" align ="center" valign="middle">安全大检查</td>-->
            <!--<td>动员部署</td>-->
            <!--<td>2020年3月</td>-->
            <!--<td>已完成</td>  			</tr>-->
            <!--<tr> <td>安全隐患排查</td>-->
            <!--<td>2020年6月-10月</td>-->
            <!--<td>30%</td>  			</tr>-->
                <!--<tr> <td>安全形式分析</td>-->
            <!--<td>2020年6月-12月</td>-->
            <!--<td>40%</td>  			</tr>-->
</table>
    </div>
       {{ 用户的POST请求 }}

  {% endblock 主体 %}

        {% block 主页高亮 %}
active
{% endblock 主页高亮 %}

to_do_list-final/my_app/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form action="">
    {%csrf_token%}
    <p>用户名：</p>
    <input type="text" name="username"/>
    <p>密码：{{ a }}</p>
    <input type="text" name="password"/>
    <input type="submit"/>

</form>
</body>
</html>

to_do_list-final/my_app/templates/search.html
{% extends "base.html" %}
{% load static %}
{% block css %}{% static 'my_app/home.css' %}{% endblock css %}
{% block 主体 %}
<!--<body>-->
    <!--<form action="/search/">-->
        <!--<input name="big_subject" class="form-control mr-sm-2" type="text" placeholder="添加计划" aria-label="Search">-->
         <!--<input name="task" class="form-control mr-sm-2" type="text" placeholder="添加计划" aria-label="Search">-->
         <!--<input name="activity" class="form-control mr-sm-2" type="text" placeholder="添加计划" aria-label="Search">-->
        <!--<input name="input_time" class="form-control mr-sm-2" type="text" placeholder="添加计划" aria-label="Search">-->
        <!--<input name="end_time" class="form-control mr-sm-2" type="text" placeholder="添加计划" aria-label="Search">-->
      <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>-->
    <!--</form>-->
    <!--</div>-->
<!--</body>-->

<body>
  <form id="form_edit" action=" " method = "post">
         <div class="form-rol">
        {%csrf_token %}
             <div>
                 <p>查询相关时间段、内容、进度的各项工作
                 </p>
             </div>
    <div class="col">
         {{ form }} <br>
    </div>
<button class="btn btn-primary" type="submit"   /> 查询条目 <br>
         </div>

    </form>

<table class="table table-hover">

  <thead class="thead-light">
            <tr align="center">
                <th scope="col">序号</th>
              <th scope="col">工作类别</th>
            <th scope="col">活动名称</th>
            <th scope="col">具体项目</th>
            <th scope="col">开始时间</th>
                <th scope="col">结束时间</th>
            <th scope="col">工作进度</th>
            </tr>
  </thead>
     {% for activity in act_list %}
    <tr>
        <th scope="row"> {{forloop.counter}}</th>
    <td rowspan="1">{{ activity.task.big_subject }}
    </td>
          <td rowspan="1">{{ activity.task }}
    </td>
        <td rowspan="1">{{ activity.name }}
    </td>
           <td rowspan="1">{{ activity.start_time }}
    </td>
          <td rowspan="1">{{ activity.end_time }}
    </td>
          <td rowspan="1">{{ activity.progress }}
    </td>

    </tr>
    {% endfor %}

</body>

  {% endblock 主体 %}

        {% block 搜索高亮 %}
active
{% endblock 搜索高亮 %}